# Generated by Django 3.2.9 on 2021-12-17 11:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_enrolled_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
