# Generated by Django 3.2.9 on 2021-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20211220_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
