# Generated by Django 2.2.7 on 2022-01-04 17:40

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20220104_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_img/default.jpg', upload_to=course.models.upload_img),
        ),
    ]
