# Generated by Django 2.2.7 on 2022-01-04 18:47

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='payment_img/default.jpg', upload_to=course.models.upload_payment_img)),
            ],
        ),
    ]
