# Generated by Django 2.2.7 on 2022-01-04 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 4, 18, 52, 55, 815450, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
