# Generated by Django 3.2.9 on 2021-12-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Saad Khan', max_length=60),
            preserve_default=False,
        ),
    ]
